/**
 * Copyright (C) @2025 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Created by @juliswang on 2025/04/29 20:19
 *
 * @Description
 */
export default class AppConfig {
  static BASE_URL: string = "https://julis.wang/";
  static AVATAR: string = "https://julis.wang/img/avatar.png";
  static BLOG_URL: string = "https://julis.wang";
  static BLOG_NAME: string = "落叶挽歌";
  static BLOG_DESC: string = "juliswang's 博客";
}
